freeboard/urls.py
from django.urls import path

from .views import *



app_name = 'freeboard'
urlpatterns = [

    # Example: /
    path('', FreeboardLV.as_view(), name='freeboard_list'),

    # Example: /freeboard/99/
    path('<int:pk>/', FreeboardDV.as_view(), name='freeboard_detail'),

    # Example: /freeboard/add/
    path('add/', FreeboardCreateView.as_view(), name="freeboard_add"),

    # Example: /freeboard/change/
    path('change/', FreeboardChangeLV.as_view(), name="freeboard_change"),

    # Example: /photo/99/update/
    path('<int:pk>/update/', FreeboardUpdateView.as_view(), name="freeboard_update"),

    # Example: /freeboard/99/delete/
    path('<int:pk>/delete/', FreeboardDeleteView.as_view(), name="freeboard_delete"),
    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
path('admin/', admin.site.urls),
path('', wordcount.views.home, name="home"),
path('about/', wordcount.views.about, name="about"),
path('result/', wordcount.views.result, name = "result"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserCreateView, UserCreateDoneTV, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('post/', include('photo.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('showme/', include('showme.urls')),
    path('produce/', include('produce.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from .views import *



app_name = 'photo'
urlpatterns = [

    # Example: /
    path('', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    path('album/', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),

    # Example: /album/99/like/
    path('album/<int:pk>/like/', AlbumDV2.as_view(), name='album_detail2'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/add/
    path('photo/add/', PhotoCreateView.as_view(), name="photo_add"),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name="photo_update"),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name="photo_delete"),

    # Example: photo/change/
    path('photo/change/', PhotoChangeLV2.as_view(), name="photo_change_list"),

    # Example: /mypage
    path('mypage/', PhotoChangeLV.as_view(), name="photo_change"),
    
]

freeboard/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User 

# Create your models here.
class Freeboard(models.Model):
    title = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('Upload Date', auto_now_add = True)
    body = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
    		return self.title

    def get_absolute_url(self):
        return reverse('freeboard:freeboard_detail', args=(self.id,))

    class Meta:
        ordering = ['-pub_date']

    def title_summary(self):
        return self.title[:40]

freeboard/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Freeboard
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import HttpResponseRedirect,HttpResponse
from photo.models import Album


class FreeboardLV(ListView):
    model = Freeboard

    def get_context_data(self, **kwargs):
        context = super(FreeboardLV, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context

class FreeboardDV(DetailView):
    model = Freeboard

    def get_context_data(self, **kwargs):
        context = super(FreeboardDV, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context

#--- Add/Change/Update/Delete for Freeboard
class FreeboardCreateView(LoginRequiredMixin, CreateView):
    model = Freeboard
    fields = ['title', 'body']
    success_url = reverse_lazy('freeboard:freeboard_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(FreeboardCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(FreeboardCreateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context    


class FreeboardChangeLV(LoginRequiredMixin, ListView):
    template_name = 'freeboard/freeboard_change_list.html'

    def get_queryset(self):
        return Freeboard.objects.filter(owner=self.request.user)


class FreeboardUpdateView(LoginRequiredMixin, UpdateView):
    model = Freeboard
    fields = ['title', 'body']
    success_url = reverse_lazy('freeboard:freeboard_list')

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.owner != request.user:
            messages.info(request, '수정할 권한이 없습니다!')
            return HttpResponseRedirect('/freeboard/')
        else:
            return super(FreeboardUpdateView, self).dispatch(request, *args, **kwargs)
    
    def get_context_data(self, **kwargs):
        context = super(FreeboardUpdateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context 


class FreeboardDeleteView(LoginRequiredMixin, DeleteView):
    model = Freeboard
    success_url = reverse_lazy('freeboard:freeboard_list')
    
    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.owner != request.user:
            messages.info(request, '삭제할 권한이 없습니다!')
            return HttpResponseRedirect('/freeboard/')
        else:
            return super(FreeboardDeleteView, self).dispatch(request, *args, **kwargs)

freeboard/templates/freeboard/freeboard_change_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
    table {
    border-collapse: collapse;
    }

    td, th {
        line-height: 18px;
        border-bottom: 1px solid #eee;
        vertical-align: top;
        padding: 5px 15px;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    }

    table.change-list, table.change-list th, table.change-list td {
        border: 1px solid #ccc;
    }


    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
    <title>ILoveUT</title>
  </head>
  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61146465_2707254312682873_6836619136638910464_n.jpg?_nc_cat=102&_nc_ht=scontent-icn1-1.xx&oh=65f0de25fc430618ef3da8408e4f3b2c&oe=5D6286F4" width="138" height="100"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61082517_2707254306016207_549443793103880192_n.jpg?_nc_cat=105&_nc_ht=scontent-icn1-1.xx&oh=10fe92140283d8da6ccffcee393c7472&oe=5D676987"></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            
            {% if user.is_active %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_change'%}">{% firstof user.get_short_name user.get_username %}님</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_add' %}">글쓰기</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'register' %}">회원가입</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Login</a>
            {% endif %}
                     
          </div>
        </div>
      </header>
      <hr>
<br><br>
<div id="content">

    <h1>자유게시글 - {{user}}</h1>

    <br><br>
    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.body }}</td>
            <td><a href="{% url 'freeboard:freeboard_update' item.id %}">Update</a></td>
            <td><a href="{% url 'freeboard:freeboard_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
  </div>
  </body>
</html>

freeboard/templates/freeboard/freeboard_confirm_delete.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
    table {
    border-collapse: collapse;
    }

    td, th {
        line-height: 18px;
        border-bottom: 1px solid #eee;
        vertical-align: top;
        padding: 5px 15px;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    }

    table.change-list, table.change-list th, table.change-list td {
        border: 1px solid #ccc;
    }


    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
    <title>ILoveUT</title>
  </head>
  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61146465_2707254312682873_6836619136638910464_n.jpg?_nc_cat=102&_nc_ht=scontent-icn1-1.xx&oh=65f0de25fc430618ef3da8408e4f3b2c&oe=5D6286F4" width="138" height="100"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61082517_2707254306016207_549443793103880192_n.jpg?_nc_cat=105&_nc_ht=scontent-icn1-1.xx&oh=10fe92140283d8da6ccffcee393c7472&oe=5D676987"></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            
            {% if user.is_active %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_change'%}">{% firstof user.get_short_name user.get_username %}님</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_add' %}">글쓰기</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'register' %}">회원가입</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Login</a>
            {% endif %}
                     
          </div>
        </div>
      </header>
      <hr>
<div id="content">
<br><br>

    <h1>자유게시글 지우기</h1>

    <form action="." method="post">{% csrf_token %}
        <p>정말 <strong>"{{ object }}"</strong> 를 지우시겠습니까? ?</p>
        <input type="submit" value="네!!" />
    </form>
    <br>
    <p><a href="{% url 'freeboard:freeboard_list' %}">돌아가기</a></p>

  </div>
  </body>
</html>

freeboard/templates/freeboard/freeboard_detail.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
        
            <div class="card">
              <div class="card-header">
                {{object.title}}    
              </div>
              <div class="card-body">
                <p class="card-text" style="float:right">{{object.pub_date|date:"m.d A f"}}, {{object.owner}}</p><br>
                <p class="card-text">{{object.body|linebreaks}}</p>
              </div>
            </div>
            <br>
            
          <div style="float: right" class="btn-toolbar" role="toolbar" aria-label="Toolbar with button groups">
              <div class="btn-group mr-2" role="group" aria-label="First group">
                  <a href="{% url 'freeboard:freeboard_delete' object.id %}"><button type="button" class="btn btn-secondary">삭제하기</button></a>
              </div>
              
              <div class="btn-group mr-2  " role="group" aria-label="Second group">
                  <a href="{% url 'freeboard:freeboard_update' object.id %}"><button type="button" class="btn btn-secondary">수정하기</button></a>
              </div>
              <div class="btn-group" role="group" aria-label="Third group">
                  <button type="button" class="btn btn-secondary">뒤로가기</button>
              </div>
          </div>
            <br/><br><br>
    <div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
    </div>

    {%endblock%}

freeboard/templates/freeboard/freeboard_form.html
{% extends "base.html" %}

{% block title %}freeboard_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
<div id="content">

    <h1>게시글 올리기 - {{user}}님</h1>

    {% if form.is_multipart %}
    <form enctype="multipart/form-data" method="post" action=".">
    {% else %}
    <form method="post" action=".">
    {% endif %}
    {% csrf_token %}

    {% if form.errors %}
    <p class="errornote">Wrong! Please correct the error(s) below.</p>
    {% endif %}

    <p>게시글을 올리거나 수정할 수 있는 페이지</p>

    <fieldset class="aligned">

        <div class="form-row">
            {{ form.title.label_tag }} {{ form.title }}
        </div>

        <div class="form-row">
            {{ form.body.label_tag }} {{ form.body }}
            
        </div>



    </fieldset>

    <div class="submit-row">
        <input type="submit" value="Submit"/>
    </div>

    <script type="text/javascript">document.getElementById('id_freeboard').focus();</script>

    </form>

</div>
{% endblock %}

freeboard/templates/freeboard/freeboard_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    {% if message.tags %} {% endif %}{{ message }}
    {% endfor %}
</ul>
{% endif %}
    <div>
        <div style="float: right" class="btn-group">
          <a class="btn btn-mr-sm-2 btn-secondary" href= "{% url 'freeboard:freeboard_add' %}">글쓰기</a>
        </div>
        <div style="float: right" class="col-4 d-flex justify-content-end align-items-center">
          <a class="text-muted" href="#">
          <form class="form-inline mt-2 mt-md-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            <button class="btn btn-secondary btn-sm" type="submit">Search</button>
          </form>
          </a>
        </div>
      </div>
      <br><br>

      <table class="table">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th style="width:60%" scope="col">제목</th>
            <th scope="col">작성자</th>
            <th scope="col">작성일</th>
            <th scope="col">조회수</th>
          </tr>
        </thead>

      {% for freeboard in object_list%}
        <tbody>
          <tr>
            <th scope="row">{{ forloop.revcounter }} </th>
            <td><a href="{% url 'freeboard:freeboard_detail' freeboard.id %}" class="text-dark">{{freeboard.title_summary}}</a></td>
            <td>{{freeboard.owner}}</td>
            <td>{{freeboard.pub_date|date:"m.d A f"}}</td>
            <td></td>
          </tr>
        </tbody>
      
      {% endfor %}
      </table>
{% endblock %}