myapp/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
path('admin/', admin.site.urls),
path('', wordcount.views.home, name="home"),
path('about/', wordcount.views.about, name="about"),
path('result/', wordcount.views.result, name = "result"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserCreateView, UserCreateDoneTV, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('post/', include('photo.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('showme/', include('showme.urls')),
    path('produce/', include('produce.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

showme/urls.py
from django.urls import path
from .views import *
import showme.views



show = showme.views


app_name = 'showme'
urlpatterns = [
    path('',show.content, name='idea_list'),
    path('idea_detail/<int:idea_id>/',show.ideadetail, name='idea_detail'),
    path('idea_detail/<int:idea_id>/delete',show.ideadelete, name='idea_delete'),
    path('add/',show.ideaadd, name='add'),
    path('create/', show.create, name='create'),
]

showme/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User 

# Create your models here.
class Showmethe(models.Model):
    title = models.CharField(max_length = 200)
    pub_date = models.DateTimeField('Upload Date', auto_now_add = True)
    body = models.TextField()
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
    		return self.title

    
    class Meta:
        ordering = ['-pub_date']

    def title_summary(self):
        return self.title[:40]

showme/views.py
from django.shortcuts import render , get_object_or_404, redirect
from .models import Showmethe
from django.utils import timezone

from .models import Showmethe


def content(request):
    items = Showmethe.objects
    return render(request,'idea_list.html', {'items':items})

def ideadetail(request, idea_id):
    id_detail = get_object_or_404(Showmethe, pk=idea_id)
    return render(request, 'idea_detail.html', {'item':id_detail})

def ideadelete(request, idea_id):
    item = Showthe.objects.get(id = idea_id)
    item.delete()
    return redirect('')


def ideaadd(request):
    return render(request,'idea_form.html')


def create(request):
    abc = Showmethe()
    abc.title = request.GET['title']
    abc.body = request.GET['body']
    abc.pub_date = timezone.datetime.now()
    abc.save()
    return redirect('/showme/')

showme/templates/idea_detail.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
        
            <div class="card">
              <div class="card-header">
                {{item.title}}    
              </div>
              <div class="card-body">
                <p class="card-text" style="float:right">{{item.pub_date|date:"m.d A f"}} {{object.owner}}</p><br>
                <p class="card-text">{{item.body|linebreaks}}</p>
              </div>
            </div>
            <br>
            
    {% load disqus_tags %}
    {% disqus_show_comments %}
    </div>

    {%endblock%}

showme/templates/idea_form.html
{% extends "base.html" %}

{% block title %}freeboard_form.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br>
    <div class="container">
    	<form action="{%url 'showme:create' %}">
    	  <h4>제목: </h4>
    	  <input type="text" name="title">
    	  <br>
    	  <br>
    	  <h4>본문: </h4>
    	  <textarea cols=40 rows=10 name="body"></textarea>
    	  <br>
    	  <br>
    	  <input class="btn btn-dark" type="submit" value="제출하기">
      </form>
    </div>
{% endblock %}

showme/templates/idea_list.html
{% extends "base.html" %}

{% block title %}album_list.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
      <div class="card mb-3">
          <img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/67976526_2906032179471751_1335620840623964160_o.jpg?_nc_cat=104&_nc_oc=AQnG_Fb6hBRfiprV4Ag6Rvx9XY-TnKtDq5LGRwhF3GfNcnYRYJR2ExLVy5DHiijpRVw&_nc_ht=scontent-icn1-1.xx&oh=7d29247cb0495a354770bcdb40682416&oe=5DDC59A2"  class="card-img-top" alt="...">
          <div class="card-body">
            <h5 class="card-title text-center">쇼미더 아이디어!</h5>
            <p class="card-text text-center">쇼미더 아이디어는 당신이 평소에 재미있다고 생각 했던 컨텐츠를 신입 유튜버들에게 '아이디어 품앗이'를 제공해주는 기획입니다.</p>
            <p class="card-txet text-center">※아이디어를 사용하시는 유튜버분들은 작성자의 닉네임 혹은 실명을 반드시 밝혀야 함을 알립니다.</p>
            <a href="{% url 'showme:add' %}" style="text-decoration:none"><button type="button" class="btn btn-secondary btn-lg btn-block">글쓰기</button></a>
          </div>
        </div>



      <br>
      <br>
      <br>
      <br>
      <table class="table">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th style="width:60%" scope="col">제목</th>
              <th scope="col">작성자</th>
              <th scope="col">작성일</th>
              <th scope="col">조회수</th>
            </tr>
          </thead>
      
      {% for item in items.all%}
      <tbody>
          <tr>
            <th scope="row">{{ forloop.revcounter }} </th>
            <td><a href="{% url 'showme:idea_detail' item.id %}" class="text-dark">{{item.title}}</a></td>
            <td>{{item.owner}}</td>
            <td>{{item.pub_date|date:"m.d A f"}}</td>
            <td></td>
          </tr>
        </tbody>
      {% endfor %}
{% endblock %}