freeboard/urls.py
from django.urls import path

from .views import *



app_name = 'freeboard'
urlpatterns = [

    # Example: /
    path('', FreeboardLV.as_view(), name='freeboard_list'),

    # Example: /freeboard/99/
    path('<int:pk>/', FreeboardDV.as_view(), name='freeboard_detail'),

    # Example: /freeboard/add/
    path('add/', FreeboardCreateView.as_view(), name="freeboard_add"),

    # Example: /freeboard/change/
    path('change/', FreeboardChangeLV.as_view(), name="freeboard_change"),

    # Example: /photo/99/update/
    path('<int:pk>/update/', FreeboardUpdateView.as_view(), name="freeboard_update"),

    # Example: /freeboard/99/delete/
    path('<int:pk>/delete/', FreeboardDeleteView.as_view(), name="freeboard_delete"),
    
]

myapp/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
path('admin/', admin.site.urls),
path('', wordcount.views.home, name="home"),
path('about/', wordcount.views.about, name="about"),
path('result/', wordcount.views.result, name = "result"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserCreateView, UserCreateDoneTV, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('post/', include('photo.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('showme/', include('showme.urls')),
    path('produce/', include('produce.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from .views import *



app_name = 'photo'
urlpatterns = [

    # Example: /
    path('', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    path('album/', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),

    # Example: /album/99/like/
    path('album/<int:pk>/like/', AlbumDV2.as_view(), name='album_detail2'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/add/
    path('photo/add/', PhotoCreateView.as_view(), name="photo_add"),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name="photo_update"),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name="photo_delete"),

    # Example: photo/change/
    path('photo/change/', PhotoChangeLV2.as_view(), name="photo_change_list"),

    # Example: /mypage
    path('mypage/', PhotoChangeLV.as_view(), name="photo_change"),
    
]

photo/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User 

from .fields import ThumbnailImageField
from hitcount.models import HitCountMixin



class Album(models.Model):
    name = models.CharField(max_length=50)
    description = models.CharField('One Line Description', max_length=100, blank=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('photo:album_detail', args=(self.id,))



class Photo(models.Model, HitCountMixin):
    album = models.ForeignKey('Album', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = ThumbnailImageField(upload_to='photo/%Y/%m')
    description = models.TextField('Description', blank=True)
    upload_date = models.DateTimeField('Upload Date', auto_now_add=True)
    video_link = models.URLField('Youtube Link', null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    post_hit = models.PositiveIntegerField(default=0)

    class Meta:
        ordering = ['-upload_date']

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('photo:photo_detail', args=(self.id,))

    @property
    def update_counter(self):
        self.post_hit = self.post_hit + 1
        self.save()

photo/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from .models import Album, Photo
from freeboard.models import Freeboard



class AlbumLV(ListView):
    model = Album
    context_object_name = 'album'

class AlbumDV(DetailView):
    model = Album

    def get_context_data(self, **kwargs):
        # 기본 구현을 호출해 context를 가져온다.
        context = super(AlbumDV, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['album'] = Album.objects.all()
        return context

class AlbumDV2(DetailView):
    model = Album
    template_name = 'photo/album_detail2.html'

    def get_context_data(self, **kwargs):
        # 기본 구현을 호출해 context를 가져온다.
        context = super(AlbumDV2, self).get_context_data(**kwargs)
        # 모든 책을 쿼리한 집합을 context 객체에 추가한다.
        context['album'] = Album.objects.all()
        return context


class PhotoDV(DetailView):
    model = Photo

    def get_context_data(self, **kwargs):
        context = super(PhotoDV, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context

#--- Add/Change/Update/Delete for Photo
class PhotoCreateView(LoginRequiredMixin, CreateView):
    model = Photo
    fields = ['album', 'title', 'image', 'video_link', 'description']
    success_url = reverse_lazy('photo:index')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PhotoCreateView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        context = super(PhotoCreateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context


class PhotoChangeLV(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(PhotoChangeLV, self).get_context_data(**kwargs)
        context['freeboard'] = Freeboard.objects.filter(owner=self.request.user)
        return context

class PhotoChangeLV2(LoginRequiredMixin, ListView):
    template_name = 'photo/photo_change_list_2.html'

    def get_queryset(self):
        return Photo.objects.filter(owner=self.request.user)

class PhotoUpdateView(LoginRequiredMixin, UpdateView) :
    model = Photo
    fields = ['album', 'title', 'image', 'video_link', 'description']
    success_url = reverse_lazy('photo:index')

    def get_context_data(self, **kwargs):
        context = super(PhotoUpdateView, self).get_context_data(**kwargs)
        context['album'] = Album.objects.all()
        return context


class PhotoDeleteView(LoginRequiredMixin, DeleteView) :
    model = Photo
    success_url = reverse_lazy('photo:index')

photo/templates/photo/album_detail.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<br><br>
    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>
    <div>
            <div style="float: right" class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'photo:album_detail' object.id %}"><button type="button" class="btn btn-secondary">최신수</button></a>
            <a href="{% url 'photo:album_detail2' object.id %}"><button type="button" class="btn btn-secondary">조회수</button></a>
            </div>
                    
            <div style="float: right" class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                    <form class="form-inline mt-2 mt-md-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-secondary btn-sm" type="submit">Search</button>
                    </form>
                </a>
            </div>
        </div>
        <br><br>
    <hr/>

        {% for photo in object.photo_set.all %}
        
        <div class="container">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <a href="{{ photo.get_absolute_url }}">
                    <img src="{{ photo.image.thumb_url }}"
                        class="card-img" alt="...">
                    </a>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{photo.title}}</h5>
                        <p class="card-text">{{photo.description|slice:":280"}}</p>
                        <p class="card-text"><small class="text-muted">조회수 {{ photo.post_hit }}</small></p>
                        <p class="card-text"><small class="text-muted">{{ photo.upload_date|date:"m.d P" }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>

{% endblock %}

photo/templates/photo/album_detail2.html
{% extends "base.html" %}

{% block title %}album_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% static "photo/photo.css" %}{% endblock %}

{% block content %}
<br><br>
    <h2 style="display:inline">{{ object.name }}</h2>
    &emsp;<b><i>{{ object.description }}</i></b>
    <div>
            <div style="float: right" class="btn-group" role="group" aria-label="Basic example">
            <a href="{% url 'photo:album_detail' object.id %}"><button type="button" class="btn btn-secondary">최신수</button></a>
            <a href="{% url 'photo:album_detail2' object.id %}"><button type="button" class="btn btn-secondary">조회수</button></a>
            </div>
            <div style="float: right" class="col-4 d-flex justify-content-end align-items-center">
                <a class="text-muted" href="#">
                    <form class="form-inline mt-2 mt-md-0">
                        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
                        <button class="btn btn-secondary btn-sm" type="submit">Search</button>
                    </form>
                </a>
            </div>
        </div>
        <br><br>
    <hr/>

        {% for photo in object.photo_set.all|dictsort:"post_hit"%}
        <div class="container">
            <div class="row no-gutters">
                <div class="col-md-3">
                    <a href="{{ photo.get_absolute_url }}">
                    <img src="{{ photo.image.thumb_url }}"
                        class="card-img" alt="...">
                    </a>
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">{{photo.title}}</h5>
                        <p class="card-text">{{photo.description|slice:":280"}}</p>
                        <p class="card-text"><small class="text-muted">조회수 {{ photo.post_hit }}</small></p>
                        <p class="card-text"><small class="text-muted">{{ photo.upload_date|date:"m.d P" }}</small></p>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        {% endfor %}
    </div>

{% endblock %}

photo/templates/photo/photo_change_list.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      
      }
      .errornote {
          display: block;
          margin: 5px 0;
          border: 1px solid #c30;
          background: #fcf;
          padding: 5px 25px;
          color: #c30;
          font-size: 12px;
          font-weight: bold;
      }

      /* Authentication Forms */

      fieldset {
          border: 1px solid #ccc;
      }

      .aligned label {
          float: left;
          width: 170px;
          padding: 3px 10px 0 0;
      }

      .form-row {
          padding: 10px;
          font-size: 11px;
          border-bottom: 1px solid #eee;
      }

      .submit-row {
          margin: 5px 0;
          border: 1px solid #ccc;
          text-align: right;
      }

      .submit-row input {
          margin: 10px;
          background: #ffc;
      }
      

    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
    <title>ILoveUT</title>
  </head>
  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61146465_2707254312682873_6836619136638910464_n.jpg?_nc_cat=102&_nc_ht=scontent-icn1-1.xx&oh=65f0de25fc430618ef3da8408e4f3b2c&oe=5D6286F4" width="138" height="100"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61082517_2707254306016207_549443793103880192_n.jpg?_nc_cat=105&_nc_ht=scontent-icn1-1.xx&oh=10fe92140283d8da6ccffcee393c7472&oe=5D676987"></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            
            {% if user.is_active %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_change'%}">{% firstof user.get_short_name user.get_username %}님</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_add' %}">글쓰기</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'register' %}">회원가입</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Login</a>
            {% endif %}
                     
          </div>
        </div>
      </header>
      <hr>
  <div class="d-flex align-items-center p-3 my-3 text-gray-dark bg-purple rounded shadow-sm">
    <img class="mr-3" src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTT5Q49uVWtJvlvP-dHlvc-V9iU0hMrqOWYXgkVkTLLmSa5btd2" alt="" width="100" height="100">
    <div class="lh-100">
      <h5 class="mb-0 text-gray-dark lh-100">{{user}}님의 MyPage</h5>
      <small>{{user}} 소개</small>
      <br>
      <a href="https://www.youtube.com/"><small>{{user}} 유튜브 링크</small></a>
      <br>
      <input type="button" name="modify" value="수정" class="btn btn-outline-primary btn-sm" float="right">
    </div>
  </div>

  

 <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">{{user}}님의 게시글 항목</h6>
    {% for item in object_list|slice:":3" %}
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="64" height="64" src="{{ item.image.thumb_url }}" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#e83e8c"/><text x="50%" y="50%" fill="#e83e8c" dy=".3em">32x32</text></svg>
      <p class="media-body pb-2 mb-0 small lh-125 border-bottom border-gray">
        <a href="{{ item.get_absolute_url }}">
        <strong class="d-block text-gray-dark">{{ item.title}}</strong>
        {{item.description|slice:":140" }}...
        </a>
      
        <small class="d-block text-right mt-3" >
            <a href="{% url 'photo:photo_update' item.id %}">수정하기</a>
            &nbsp; &nbsp;
            <a href="{% url 'photo:photo_delete' item.id %}">삭제하기</a>
        </small> 
      </p>
    </div>
    {% endfor %}
    <small class="d-block text-right mt-3">
      <a href="{% url 'photo:photo_change_list'%}">All updates</a>
    </small>
  </div>
  
  <div class="my-3 p-3 bg-white rounded shadow-sm">
    <h6 class="border-bottom border-gray pb-2 mb-0">{{user}}님의 자유게시글 항목</h6>
    {% for post in freeboard|slice:":3" %}
    <div class="media text-muted pt-3">
      <svg class="bd-placeholder-img mr-2 rounded" width="64" height="64" xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice" focusable="false" role="img" aria-label="Placeholder: 32x32"><title>Placeholder</title><rect width="100%" height="100%" fill="#007bff"/><text x="50%" y="50%" fill="#007bff" dy=".3em">32x32</text></svg>
      <div class="media-body pb-3 mb-0 small lh-125 border-bottom border-gray">
        <a href="{{ post.get_absolute_url }}">
        <div class="d-flex justify-content-between align-items-center w-100">
          <strong class="text-gray-dark">{{post.title}}</strong>
        </div>
        <span class="d-block">{{post.body|slice:":115"}}</span>
        </a>
        <small class="d-block text-right mt-3" >
            <a href="{% url 'freeboard:freeboard_update' post.id %}">수정하기</a>
            &nbsp; &nbsp;
            <a href="{% url 'freeboard:freeboard_delete' post.id %}">삭제하기</a>
        </small> 
      </div>
    </div>
    {%endfor%}
    <small class="d-block text-right mt-3">
      <a href="{% url 'freeboard:freeboard_change'%}">All posts</a>
    </small>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script>window.jQuery || document.write('<script src="/docs/4.3/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="/docs/4.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o" crossorigin="anonymous"></script>
        <script src="offcanvas.js"></script>

          </div>
  </body>
</html>
  

photo/templates/photo/photo_change_list_2.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
    table {
    border-collapse: collapse;
    }

    td, th {
        line-height: 18px;
        border-bottom: 1px solid #eee;
        vertical-align: top;
        padding: 5px 15px;
        font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    }

    table.change-list, table.change-list th, table.change-list td {
        border: 1px solid #ccc;
    }


    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
    <title>ILoveUT</title>
  </head>
  <body>
    <div class="container">
      <header class="blog-header py-3">
        <div class="row flex-nowrap justify-content-between align-items-center">
          <div class="col-4 pt-1">
            <a class="text-muted" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61146465_2707254312682873_6836619136638910464_n.jpg?_nc_cat=102&_nc_ht=scontent-icn1-1.xx&oh=65f0de25fc430618ef3da8408e4f3b2c&oe=5D6286F4" width="138" height="100"></a>
          </div>
          <div class="col-4 text-center">
            <a class="blog-header-logo text-dark" href="{% url 'photo:index' %}"><img src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/61082517_2707254306016207_549443793103880192_n.jpg?_nc_cat=105&_nc_ht=scontent-icn1-1.xx&oh=10fe92140283d8da6ccffcee393c7472&oe=5D676987"></a>
          </div>
          <div class="col-4 d-flex justify-content-end align-items-center">
            
            {% if user.is_active %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_change'%}">{% firstof user.get_short_name user.get_username %}님</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'photo:photo_add' %}">글쓰기</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'register' %}">회원가입</a>
            <a class="btn btn-sm btn-outline-secondary" href="{% url 'login' %}">Login</a>
            {% endif %}
                     
          </div>
        </div>
      </header>
      <hr>
<br><br>
<div id="content">

    <h1>자유게시글 - {{user}}</h1>
    <br><br>
    <table class="change-list">
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th>Update</th>
            <th>Delete</th>
        </tr>
    
        {% for item in object_list %}
        <tr>
            <td>{{ item.title }}</td>
            <td>{{ item.description|slice:":55"|linebreaks }}</td>
            <td><a href="{% url 'photo:photo_update' item.id %}">Update</a></td>
            <td><a href="{% url 'photo:photo_delete' item.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </table>

</div>
  </div>
  </body>
</html>

photo/templates/photo/photo_confirm_delete.html
{% extends "base.html" %}

{% block title %}photo_confirm_delete.html{% endblock %}

{% block content %}
<div id="content">

    <h1>Photo Delete</h1>

    <form action="" method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" />
    </form>

</div>
{% endblock %}

photo/templates/photo/photo_detail.html
{% extends "base.html" %}

{% block title %}photo_detail.html{% endblock %}

{% load staticfiles %}
{% block extrastyle %}{% endblock %}

{% block content %}
<br><br>
<div>
    <h2 style="display: inline">{{ object.title }}</h2>
    <p class="text-muted " style="float : right">{{object.owner}}<br> {{ object.upload_date|date:"y.m.d" }}</p>
</div>
    <hr>
    
    <table class="photo-detail">
    <tr>
    <div>
    <iframe width="560" height="315" src="{{object.video_link}}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
    </div>
    
    <td>
        {% if object.description %}<p>{{ object.description|linebreaks }}</p>
        <p style="display: none">{{ photo.update_counter }}</p>
        <p class="card-text"><small class="text-muted">조회수 {{ photo.post_hit }}</small></p>
        {% else %}<p>(blank)</p>{% endif %}
        <p><a href="{% url 'photo:album_detail' object.album.id %}">{{ object.album.name }}</a></p>
    </td>
    </tr></table>

    <br/>
    <div>
    {% load disqus_tags %}
    {% disqus_show_comments %}
    </div>

{% endblock %}