myapp/urls.py
from django.contrib import admin
from django.urls import path


urlpatterns = [
path('admin/', admin.site.urls),
path('', wordcount.views.home, name="home"),
path('about/', wordcount.views.about, name="about"),
path('result/', wordcount.views.result, name = "result"),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from .views import UserCreateView, UserCreateDoneTV, HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'),
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),
    path('post/', include('photo.urls')),
    path('freeboard/', include('freeboard.urls')),
    path('showme/', include('showme.urls')),
    path('produce/', include('produce.urls')),
]  + static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path

from .views import *



app_name = 'photo'
urlpatterns = [

    # Example: /
    path('', AlbumLV.as_view(), name='index'),

    # Example: /album/, same as /
    path('album/', AlbumLV.as_view(), name='album_list'),

    # Example: /album/99/
    path('album/<int:pk>/', AlbumDV.as_view(), name='album_detail'),

    # Example: /album/99/like/
    path('album/<int:pk>/like/', AlbumDV2.as_view(), name='album_detail2'),

    # Example: /photo/99/
    path('photo/<int:pk>/', PhotoDV.as_view(), name='photo_detail'),

    # Example: /photo/add/
    path('photo/add/', PhotoCreateView.as_view(), name="photo_add"),

    # Example: /photo/99/update/
    path('photo/<int:pk>/update/', PhotoUpdateView.as_view(), name="photo_update"),

    # Example: /photo/99/delete/
    path('photo/<int:pk>/delete/', PhotoDeleteView.as_view(), name="photo_delete"),

    # Example: photo/change/
    path('photo/change/', PhotoChangeLV2.as_view(), name="photo_change_list"),

    # Example: /mypage
    path('mypage/', PhotoChangeLV.as_view(), name="photo_change"),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/blog/">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      
      }
      .errornote {
          display: block;
          margin: 5px 0;
          border: 1px solid #c30;
          background: #fcf;
          padding: 5px 25px;
          color: #c30;
          font-size: 12px;
          font-weight: bold;
      }

      /* Authentication Forms */

      fieldset {
          border: 1px solid #ccc;
      }

      .aligned label {
          float: left;
          width: 170px;
          padding: 3px 10px 0 0;
      }

      .form-row {
          padding: 10px;
          font-size: 11px;
          border-bottom: 1px solid #eee;
      }

      .submit-row {
          margin: 5px 0;
          border: 1px solid #ccc;
          text-align: right;
      }

      .submit-row input {
          margin: 10px;
          background: #ffc;
      }
      

    </style>
    <!-- Custom styles for this template -->
    <link href="https://fonts.googleapis.com/css?family=Playfair+Display:700,900" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="blog.css" rel="stylesheet">
    <title>ILoveUT</title>
  </head>
  <body>
    <div class="container">
        <nav class="navbar navbar-expand-lg navbar-light bg-light fixed-top" id="navbar">
            <div class="container">
              <a class="navbar-brand custom-brand" href="/post"><img class="nav-logo" src="https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/67942584_2905683649506604_2184802876532981760_n.jpg?_nc_cat=106&_nc_oc=AQnGRUIVeEzegkGTQi1LSrdN33G8YcT_ib0NrxJHakDFOW7Icj81O-E5JVXVDlmXI_g&_nc_ht=scontent-icn1-1.xx&oh=faa9e71dc808a64e4e67e01754e049ab&oe=5DA2B2C2" alt="Logo1" /></a>
              <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse custom-nav-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                  <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownPortfolio" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                      이벤트
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdownPortfolio">
                      <a class="dropdown-item" href="/produce">프로듀스X유튜버</a>
                      <a class="dropdown-item" href="/showme">쇼미더아이디어</a>
                    </div>
                  </li>
                  <li class="nav-item" data-nav-url='/freeboard'>
                      <a class="nav-link" href="/freeboard">자유게시판</a>
                  </li>
                     {% if user.is_active %}
                     <li class="nav-item" >
                      <a class="nav-link sign" href="{% url 'photo:photo_add' %}">글쓰기</a>
                      </li>
                      <li class="nav-item" >
                      <a class="nav-link sign" href="{% url 'photo:photo_change' %}">마이페이지</a>
                      </li>
                      <li class="nav-item" >
                      <a class="nav-link sign" href="{% url 'logout' %}">로그아웃</a>
                      </li>
                      {% else %}
                      <li class="nav-item" >
                      <a class="nav-link sign" href="{% url 'register' %}">회원가입</a>
                      </li>
                      <li class="nav-item" >
                      <a class="nav-link sign" href="{% url 'login' %}">로그인</a>
                      </li>
                      {% endif %}
             
                </ul>
              </div>
              <script>
                $(window).scroll(function() {
                  var $el = $('#navbar');
                  
                  if($(this).scrollTop() >= 10) { 
                    $el.addClass('shown');
                  } else { 
                    $el.removeClass('shown');
                  }
                });
              </script>
              <script>
                /* link active set up*/
                $(function(){
                  // 페이지가 로드될때마다 이 구역이 실행됨.
                  let _pathname = location.pathname;
                  let _navItems = $('.navbar-nav').find('.nav-item');
                  for(let i = 0 ; i < _navItems.length ; i++){
                    let _currentItem = _navItems.eq(i);
                    if(_currentItem.attr('data-nav-url') === _pathname){
                      _currentItem.addClass('active');
                    }
                    else{
                      _currentItem.removeClass('active');
                    }
                  }
                });
              </script>
            </div>
          </nav>
          <br><br>
          
      </header>
      <aside>
        <div class="sidebar-sticky"
          style="width: 160px;  background: #fff; color: #fff; float: left; margin-left: -180px; margin-top: 33px">
          <ul class="list-group">
            <li style="margin-top:20px; margin-bottom:20px">
              <a class="p-2 text-muted" href="/post">&nbsp영상</a>
              <hr>
              {% for item in album %}
              <a class="p-2 text-muted" href="{% url 'photo:album_detail' item.id %}">&nbsp&nbsp&nbsp&nbsp- {{ item.name }}
                <hr></a>
              {% endfor %}
              <a class="p-2 text-muted" href="/produce">Produce X 유투버</a>
              <hr>
              <a class="p-2 text-muted" href="/showme">&nbsp쇼미더아이디어</a>
            </li>
          </ul>
        </div>
      </aside>
    
       
     
      <div class="container">
      {% block content %}
      {% endblock %}
      </div>
  </div>
  </body>
</html>

templates/home.html
<html lang="en"><head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <title>Cover Template · Bootstrap</title>


    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>

      @import url('https://fonts.googleapis.com/css?family=Noto+Sans+KR:900&display=swap&subset=korean');

      .lead{
        font-family: 'Noto Sans KR', sans-serif;
        font-size: 35px;
        color: black;

        padding-bottom:250px ;


      }
      h1{
        color: black;
        font-size: 80px;
      }
      body{
          background-image:url('https://scontent-icn1-1.xx.fbcdn.net/v/t1.0-9/67745410_2906210929453876_5158421117391601664_o.jpg?_nc_cat=107&_nc_oc=AQmEtj1YxQLlxFSr0voADrDLiD_-tyQ8wKQn7Y_G4KyNvA1iOzLMKo-X6fZ0-Exbxpg&_nc_ht=scontent-icn1-1.xx&oh=32ba4223e3872c039d1f9f1f1489d675&oe=5DE5CD40');
          
          background-size: cover;


      }


      img{

        margin: 10px;
        width: 140px;
        height: 120px;
      }
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
  <br><br><br><br><br>
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  

  <main role="main" class="inner cover">
    <h1 class="cover-heading"></h1>

    <p class="lead">
      하루하루 생겨나는 유투버!<br>
 하지만 그 진입장벽은 크다.
    </p>
     <br><br><br><br><br>
     <a href="/post">
      <button type="button" class="btn btn-danger">홈페이지로 이동</button>
    </a>
    </p>
    
  </main>

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p>Cover template for <a href="/post">Bootstrap</a>, by <a href="/post">@ILoveUT</a>.</p>
    </div>
  </footer>
</div>


</body></html>